import { Context, Fragment } from "../CompilerInterface";

export class WrapperBeforeFragment extends Fragment {

    render(ctx: Context): string {
        const argsExpr = "{\n" +
                ctx.params.map(p => "    " + p.name).join(",\n") +
            "\n  }: {\n" +
                ctx.params.map(p => "    " + p.name + ": " + p.type).join(",\n") +
            "\n  }";
        
        return (
            "// This file was generated from a topside template.\n" +
            "// Do not edit this file, edit the original template instead.\n\n" +
            ctx.imports
                .map(i => {
                    return "import " + i + ";";
                })
                .join("\n") +
            "\n\n" +
            "export default function(" +
                (ctx.params.length > 0 ? argsExpr : "") + ") {\n" +
            "    return (\n'"
        );
    }
}

export class WrapperAfterFragment extends Fragment {

    render(ctx: Context): string {
        ctx;
        return "');\n};";
    }
};
